#+TITLE: Complex Multiplier with AXI Stream Interface

** Overview
The complex multiplier has two AXI stream inputs and one AXI stream output. It can be used in SDR (Software Defined Radio) applications, where up- or down-mixing is required.

** Implementation Details
The widths of the inputs and output can be configured via the parameters INPUT_WIDTH_A, INPUT_WIDTH_B and OUTPUT_WIDTH. These parameters must be a multiple of 8.
If the output width equals INPUT_WIDTH_A + INPUT_WIDTH_B no truncation or rounding is necessary.
If the sum of the input widths is larger than the output width, truncation or rounding is necessary, which can be selected via the TRUNCATE parameter. If TRUNCATE = 1, the spare bits of the result are truncated by a right shift operation. If TRUNCATE = 0, the rounding_cy input is used to perform a rounding.


** Verification
*** Requirements for Tests
Verilator 1.4
 
Python 3.8 with modules: fixedpoint, cocotb, cocotb-test, bitstring, pytest, pytest-cov, cocotbext.axi

*** Running the tests
To run the cocotb-test based tests go into the folder of this repository and type "SIM=verilator pytest -v"

Alternatively cocotb tests can be run by using the Makefile in the tests folder. To run in go into the tests folder an type "make clean; make" 